language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install
  - nvm install v14.15.5

before_script:
  - nvm use v14.15.5

script:
  - hexo generate -f

after_script:
  - cd ./public
  - git init
  - git config user.name "wxb"
  - git config user.email "wxb0328@icloud.com"
  - git add .
  - git commit -m "Update docs by wangxb"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/wxb/wxb.github.io.git